# Generated by Django 3.2.20 on 2023-07-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='a brilliant project'),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(default='HTML', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='project', max_length=255),
        ),
    ]
